### ISSUE TITLE
Make Client a Context Manager

### ISSUE THREAD

**Issue by GrandMoff100** [janaSunrise/HypixelIO#304]
## Describe the solution you would like

I would like `Client` and `AsyncClient` to have `__exit__` (and `__enter__` of course) methods that automatically call `.close` upon being done with the client context.

## Describe alternatives you've considered

I've considered creating a subclass myself that does this but to write it from scratch in every bot/app is not optimal.

**Comment by GrandMoff100** [comment]
Feel free to assign me.

**Comment by janaSunrise** [comment]
Hi, thank you for the feature request! I would be more than happy to implement this for Client (and Async client).

But, quick question - Won't this enable making multiple instances/instantiating the client everytime you use it through context managers, making it kind-of repetitive?

It would be great if you can show me an example, and I can assign you if you're interested, or I'll integrate that through my PR #305.

**Comment by GrandMoff100** [comment]
Yay! You're welcome!

As I told you on discord you can initialize it before and reuse the object between contexts like this.

```py

client = Client(..., ...)

with client:
    ...
    
async with client:
    ...
